version: '2'
services:
  anaconda3-jupyter:
    image: anaconda3-jupyter
    container_name: anaconda3-jupyter
    ports:
     - "8888:8888"
    environment:
     - disable_password=$disable_password
     - jupyter_password=$jupyter_password
     - base_url='/'
    
    volumes:
     - ./notebooks:/opt/notebooks
